

<!--light slider-->
<div class="col-xs-12 pad0">
<div id="loader"><img class="center-block" src="<?php echo $this->getSkinUrl();?>images/rolling.gif"></div>
<div class="item">
  <ul id="content-slider" class="content-slider cs-hidden">
    <li>
        <!-- <img src="assets/img/slide1.jpg" class="img-responsive hidden-xs"> -->
        <div class="col-xs-12 pad0 text-center mob-banner ">FASTEST DOOR DELIVERY</div>
    </li>
    <li>
        <!-- <img src="assets/img/slide2.jpg" class="img-responsive hidden-xs"> -->
        <div class="col-xs-12 pad0 text-center mob-banner">QUALITY SERVICE</div>
    </li>
    <li>
        <!-- <img src="assets/img/slide3.jpg" class="img-responsive hidden-xs"> -->
        <div class="col-xs-12 pad0 text-center mob-banner ">WORLD CLASS SERVICE</div>
    </li>
  </ul>
</div>
</div>
<!--light slider-->




<!--light slider-->
<div class="col-xs-12 pad0 mt20">
<div id="loader-2"><img class="center-block" src="<?php echo $this->getSkinUrl();?>images/rolling.gif"></div>
<div class="item">
  <ul id="content-slider-2" class="content-slider cs-hidden-2">
    <li>
        <!-- <img src="assets/img/slide1.jpg" class="img-responsive hidden-xs"> -->
        <div class="col-xs-12 pad0 text-center mob-banner-2 ">Product</div>
    </li>
    <li>
        <!-- <img src="assets/img/slide2.jpg" class="img-responsive hidden-xs"> -->
        <div class="col-xs-12 pad0 text-center mob-banner-2">Product</div>
    </li>
    <li>
        <!-- <img src="assets/img/slide3.jpg" class="img-responsive hidden-xs"> -->
        <div class="col-xs-12 pad0 text-center mob-banner-2 ">Product</div>
    </li>
    <li>
        <!-- <img src="assets/img/slide1.jpg" class="img-responsive hidden-xs"> -->
        <div class="col-xs-12 pad0 text-center mob-banner-2 ">Product</div>
    </li>
    <li>
        <!-- <img src="assets/img/slide2.jpg" class="img-responsive hidden-xs"> -->
        <div class="col-xs-12 pad0 text-center mob-banner-2">Product</div>
    </li>
    <li>
        <!-- <img src="assets/img/slide3.jpg" class="img-responsive hidden-xs"> -->
        <div class="col-xs-12 pad0 text-center mob-banner-2 ">Product</div>
    </li>
  </ul>
</div>
</div>
<!--light slider-->


<div class="col-xs-12 col-sm-12 pad0 mt20">
    <?php
       
        for($i = 1; $i <= 20; $i++){
    ?>
        <div class="col-xs-10 col-sm-3 pad0 text-center products-card">Product <?php echo $i; ?></div>
    <?php
        }
    ?>
</div>
