

<!--light slider-->
<div class="col-xs-12 col-sm-2 pad0 bg-grey pad20">
    <div class="title mb10" id="catTitle">Categories <span class="pull-right"><i class="fa fa-caret-down visible-xs"></i></span></div>
    <ul id="side-menu" class="hidden-xs">
        <li><a href="javascript:void();">Sarees</a></li>
        <li><a href="javascript:void();">Bridal Lehenga</a></li>
        <li><a href="javascript:void();">Salwar Suits</a></li>
        <li><a href="javascript:void();">All Clothing</a></li>
        <li><a href="javascript:void();">Jewellery</a></li>
        <li><a href="javascript:void();">Bags</a></li>
        <li><a href="javascript:void();">Accessories</a></li>
        <li><a href="javascript:void();">Footwear</a></li>
        <li><a href="javascript:void();">Home Decor</a></li>
        <li><a href="javascript:void();">Home Furnishings</a></li>
        <li><a href="javascript:void();">Bath &amp; Beauty</a></li>
        <li><a href="javascript:void();">Food &amp; Health</a></li>
        <li><a href="javascript:void();">Gifts</a></li>
        <li><a href="javascript:void();">Kids</a></li>
        <li><a href="javascript:void();">Books</a></li>
        <li><a href="javascript:void();">Spiritual</a></li>         
    </ul>
</div>
<div class="col-xs-12 col-sm-9 col-sm-offset-1 pad0">
<div id="loader"><img class="center-block" src="<?php echo $this->getSkinUrl();?>images/rolling.gif"></div>
<div class="item">
  <ul id="content-slider" class="content-slider cs-hidden">
    <li>
        <img src="skin/frontend/rwd/default/img/01.jpg" style="width:100%;">
        
    </li>
    <li>
        <img src="skin/frontend/rwd/default/img/01.jpg" style="width:100%;">
        
    </li>
    <li>
        <img src="skin/frontend/rwd/default/img/01.jpg" style="width:100%;">
        
    </li>
  </ul>
</div>
</div>
<!--light slider-->




<!--light slider-->
<div class="col-xs-12 mt40 trending-products-heading">Trending Prodcuts</div>
<div class="col-xs-12 trending-products">
<div id="loader-2"><img class="center-block" src="<?php echo $this->getSkinUrl();?>images/rolling.gif"></div>
<div class="item">
  <ul id="content-slider-2" class="content-slider cs-hidden-2">
    <li>
        <div class="col-xs-12 pad0 text-center mob-banner-2 ">
            <img src="skin/frontend/rwd/default/img/14.jpg" class="img-responsive">
            <img src="skin/frontend/rwd/default/img/price.png" class="img-responsive center-block">
        </div>
    </li>
    <li>
        <div class="col-xs-12 pad0 text-center mob-banner-2">
            <img src="skin/frontend/rwd/default/img/14.jpg" class="img-responsive">
            <img src="skin/frontend/rwd/default/img/price.png" class="img-responsive center-block">
        </div>
    </li>
    <li>
        <div class="col-xs-12 pad0 text-center mob-banner-2 ">
            <img src="skin/frontend/rwd/default/img/14.jpg" class="img-responsive">
            <img src="skin/frontend/rwd/default/img/price.png" class="img-responsive center-block">
        </div>
    </li>
    <li>
        <div class="col-xs-12 pad0 text-center mob-banner-2 ">
            <img src="skin/frontend/rwd/default/img/14.jpg" class="img-responsive">
            <img src="skin/frontend/rwd/default/img/price.png" class="img-responsive center-block">
        </div>
    </li>
    <li>
        <div class="col-xs-12 pad0 text-center mob-banner-2">
            <img src="skin/frontend/rwd/default/img/14.jpg" class="img-responsive">
            <img src="skin/frontend/rwd/default/img/price.png" class="img-responsive center-block">
        </div>
    </li>
    <li>
        <div class="col-xs-12 pad0 text-center mob-banner-2 ">
            <img src="skin/frontend/rwd/default/img/14.jpg" class="img-responsive">
            <img src="skin/frontend/rwd/default/img/price.png" class="img-responsive center-block">
        </div>
    </li>
  </ul>
</div>
</div>
<!--light slider-->


<div class="col-xs-12 col-sm-9 pad0 mt40">
    <div class="title col-xs-12 pad0 ">Latest Products</div>
    <?php
       
        for($i = 1; $i <= 12; $i++){
    ?>
        <div class="col-xs-10 col-sm-2 pad0 text-center products-card">
            <img src="skin/frontend/rwd/default/img/12.jpg" class="img-responsive center-block">
            <img src="skin/frontend/rwd/default/img/price.png" class="img-responsive center-block">
        </div>
    <?php
        }
    ?>
</div>
<div class="col-xs-12 col-sm-3 pad0 mt40"> 
    <div class="title col-xs-12 pad0 text-center">Bestsellers</div>
    <img src="skin/frontend/rwd/default/img/bestseller.png" style="width:100%;">
</div>
