<?php
$currentCurrencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
?>

<!-- <div class="col-xs-12 col-sm-2 pad0 bg-grey pad20">
    <div class="title mb10" id="catTitle">Categories <span class="pull-right"><i class="fa fa-caret-down visible-xs"></i></span></div>
    <ul id="side-menu" class="hidden-xs">
        <li><a href="javascript:void();">Sarees</a></li>
        <li><a href="javascript:void();">Bridal Lehenga</a></li>
        <li><a href="javascript:void();">Salwar Suits</a></li>
        <li><a href="javascript:void();">All Clothing</a></li>
        <li><a href="javascript:void();">Jewellery</a></li>
        <li><a href="javascript:void();">Bags</a></li>
        <li><a href="javascript:void();">Accessories</a></li>
        <li><a href="javascript:void();">Footwear</a></li>
        <li><a href="javascript:void();">Home Decor</a></li>
        <li><a href="javascript:void();">Home Furnishings</a></li>
        <li><a href="javascript:void();">Bath &amp; Beauty</a></li>
        <li><a href="javascript:void();">Food &amp; Health</a></li>
        <li><a href="javascript:void();">Gifts</a></li>
        <li><a href="javascript:void();">Kids</a></li>
        <li><a href="javascript:void();">Books</a></li>
        <li><a href="javascript:void();">Spiritual</a></li>         
    </ul>
</div> -->
<!--light slider-->
<div class="col-xs-12 col-sm-10 col-sm-offset-1 pad0">
<div id="loader"><img class="center-block" src="<?php echo $this->getSkinUrl();?>images/rolling.gif"></div>
<div class="item">
  <ul id="content-slider" class="content-slider cs-hidden">
    <li>
        <img src="skin/frontend/rwd/default/img/01.jpg" style="width:100%;">
        
    </li>
    <li>
        <img src="skin/frontend/rwd/default/img/01.jpg" style="width:100%;">
        
    </li>
    <li>
        <img src="skin/frontend/rwd/default/img/01.jpg" style="width:100%;">
        
    </li>
  </ul>
</div>
</div>
<!--light slider-->




<!--light slider-->
<div class="col-xs-12 mt40 trending-products-heading">Trending Prodcuts</div>
<div class="col-xs-12 trending-products mb20">
<div id="loader-2"><img class="center-block" src="<?php echo $this->getSkinUrl();?>images/rolling.gif"></div>
<div class="item">
  <ul id="content-slider-2" class="content-slider cs-hidden-2">
    <?php
        $rootCatId = 3;
        $collection = Mage::getResourceModel('catalog/product_collection')
        ->joinField('category_id','catalog/category_product','category_id','product_id=entity_id',null,'left')
        ->addAttributeToFilter('category_id', array('in' => $rootCatId))
        ->addAttributeToSelect('*')
        ->load();
        $html = '';
        foreach($collection as $product){
            if($product->getSpecialPrice() && $product->getSpecialPrice() != 0){
                $discountedPrice = $product->getSpecialPrice();
                $price = $product->getPrice();
                $discount = (1 - ($discountedPrice / $price)) * 100;
                $discountHtml = '<s>'.$currentCurrencySymbol.' '.$product->getPrice().'</s>('.$discount.' % off)';
            }else{
                $discountedPrice = $product->getPrice();
                $discountHtml = '&nbsp;';
            } 
            $html .= '<li>
            <div class="col-xs-12 pad0 text-center mob-banner-2">
            <a href="'.$product->getProductUrl().'"><img src="'.$product->getImageUrl().'" class="img-responsive"></a>
            <div class="col-xs-12 col-sm-12 pad0">'.number_format($product->getName()).'</div>
            <div class="col-xs-12 col-sm-12 pad0">Price : '.$currentCurrencySymbol.' '.$discountedPrice.'</div>
            <div class="col-xs-12 col-sm-12 pad0">'.$discountHtml.'</div>
            </div>
            </li>'; 
        }
        echo $html;
    ?>
  </ul>
</div>
</div>
<!--light slider-->

<div class="col-xs-12 mt40 trending-products-heading">Trending Categories</div>
<div class="col-xs-12 col-sm-12 pad0 mb20">
    <div class="col-xs-12 col-sm-3 pad5">
        <img src="skin/frontend/rwd/default/img/p1.png" class="width100" style="min-height: 220px;">
    </div>
    <div class="col-xs-12 col-sm-3 pad5">
        <img src="skin/frontend/rwd/default/img/p2.png" class="width100" style="min-height: 220px;">
    </div>
    <div class="col-xs-12 col-sm-3 pad5">
        <img src="skin/frontend/rwd/default/img/p3.png" class="width100" style="min-height: 220px;">
    </div>
    <div class="col-xs-12 col-sm-3 pad5">
        <img src="skin/frontend/rwd/default/img/p4.png" class="width100" style="min-height: 220px;">
    </div>
</div>


<!-- <div class="col-xs-12 col-sm-9 pad0 mt40">
    <div class="title col-xs-12 pad0 ">Latest Products</div>
    <div class="col-xs-12 col-sm-12 pad0 ">
    <?php
        // $rootCatId = 3;
        // $collection = Mage::getResourceModel('catalog/product_collection')
        // ->joinField('category_id','catalog/category_product','category_id','product_id=entity_id',null,'left')
        // ->addAttributeToFilter('category_id', array('in' => $rootCatId))
        // ->addAttributeToSelect('*')
        // ->load();
        // $html = '';
        // foreach($collection as $product){
        //     if($product->getSpecialPrice() && $product->getSpecialPrice() != 0){
        //         $discountedPrice = $product->getSpecialPrice();
        //         $price = $product->getPrice();
        //         $discount = (1 - ($discountedPrice / $price)) * 100;
        //         $discountHtml = '<s>'.$currentCurrencySymbol.' '.$product->getPrice().'</s>('.$discount.' % off)';
        //     }else{
        //         $discountedPrice = $product->getPrice();
        //         $discountHtml = '&nbsp;';
        //     } 
        //     $html .= '<div class="col-xs-10 col-sm-2 pad0 text-center products-card">
        //     <a href="'.$product->getProductUrl().'"><img src="'.$product->getImageUrl().'" class="img-responsive"></a>
        //     <div class="col-xs-12 col-sm-12 pad0">'.$product->getName().'</div>
        //     <div class="col-xs-12 col-sm-12 pad0">Price : '.$currentCurrencySymbol.' '.$discountedPrice.'</div>
        //     <div class="col-xs-12 col-sm-12 pad0">'.$discountHtml.'</div>
        //             </div>'; 
        // }
        // echo $html;
    ?>
    </div>
</div>
<div class="col-xs-12 col-sm-3 pad0 mt40"> 
    <div class="title col-xs-12 pad0 text-center">Bestsellers</div>
    <img src="skin/frontend/rwd/default/img/bestseller.png" style="width:100%;">
</div> -->


<!--light slider-->
<div class="col-xs-12 mt40 trending-products-heading">Latest Prodcuts</div>
<div class="col-xs-12 trending-products mb20">
<div id="loader-3"><img class="center-block" src="<?php echo $this->getSkinUrl();?>images/rolling.gif"></div>
<div class="item">
  <ul id="content-slider-3" class="content-slider cs-hidden-3">
    <?php
        $rootCatId = 3;
        $collection = Mage::getResourceModel('catalog/product_collection')
        ->joinField('category_id','catalog/category_product','category_id','product_id=entity_id',null,'left')
        ->addAttributeToFilter('category_id', array('in' => $rootCatId))
        ->addAttributeToSelect('*')
        ->load();
        $html = '';
        foreach($collection as $product){
            if($product->getSpecialPrice() && $product->getSpecialPrice() != 0){
                $discountedPrice = $product->getSpecialPrice();
                $price = $product->getPrice();
                $discount = (1 - ($discountedPrice / $price)) * 100;
                $discountHtml = '<s>'.$currentCurrencySymbol.' '.$product->getPrice().'</s>('.$discount.' % off)';
            }else{
                $discountedPrice = $product->getPrice();
                $discountHtml = '&nbsp;';
            } 
            $html .= '<li>
            <div class="col-xs-12 pad0 text-center mob-banner-2">
            <a href="'.$product->getProductUrl().'"><img src="'.$product->getImageUrl().'" class="img-responsive"></a>
            <div class="col-xs-12 col-sm-12 pad0">'.number_format($product->getName()).'</div>
            <div class="col-xs-12 col-sm-12 pad0">Price : '.$currentCurrencySymbol.' '.$discountedPrice.'</div>
            <div class="col-xs-12 col-sm-12 pad0">'.$discountHtml.'</div>
            </div>
            </li>'; 
        }
        echo $html;
    ?>
  </ul>
</div>
</div>
<!--light slider-->



<div class="col-xs-12 mt40 trending-products-heading">Top Brands</div>
<div class="col-xs-12 col-sm-12 pad0 mb20">
    <div class="col-xs-12 col-sm-4 pad5">
        <img src="skin/frontend/rwd/default/img/b1.png" class="width100">
    </div>
    <div class="col-xs-12 col-sm-4 pad5">
        <div class="col-xs-12 col-sm-12 pad0">
            <img src="skin/frontend/rwd/default/img/b2.png" class="width100">
        </div>
        <div class="col-xs-12 col-sm-12 pad0">
            <img src="skin/frontend/rwd/default/img/b3.png" class="width100">
        </div>
    </div>
    <div class="col-xs-12 col-sm-4 pad5">
        <div class="col-xs-12 col-sm-12 pad0">
            <img src="skin/frontend/rwd/default/img/b4.png" class="width100">
        </div>
        <div class="col-xs-12 col-sm-12 pad0">
            <img src="skin/frontend/rwd/default/img/b5.png" class="width100">
        </div>
    </div>  
</div>


<div class="col-xs-12 mt20 trending-products-heading">Trending Categories</div>
<div class="col-xs-12 col-sm-12 pad0 mb20">
    <div class="col-xs-12 col-sm-6 pad5">
        <img src="skin/frontend/rwd/default/img/01.jpg" class="img-responsive">
    </div>
    <div class="col-xs-12 col-sm-6 pad5">
        <img src="skin/frontend/rwd/default/img/01.jpg" class="img-responsive">
    </div>
</div>
