<!-- mega dropdown-->

<div class="col-xs-12 col-sm-12 pad0 navbar navbar-default navbar-static-top mega-dropdown">
    <div class="container bg-black-op3">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown menu-large">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Jewellary <b class="caret"></b></a>            
                    <ul class="dropdown-menu megamenu row">
                        <li class="col-sm-3">
                            <ul>
                                <li class="dropdown-header">Categories</li>
                                <li class="divider"></li>
                                <li><a href="#">Necklace</a></li>                                
                                <li><a href="#">Anklets</a></li>                                
                                <li><a href="#">Bracelets</a></li>
                                <li><a href="#">Bangles</a></li>
                                <li><a href="#">Bajuband</a></li>
                                <li><a href="#">Ring</a></li>
                                <li><a href="#">Earings</a></li>
                            </ul>
                        </li>
                        <li class="col-sm-3">
                            <ul>
                                <li class="dropdown-header">New Collections</li>
                                <li class="divider"></li>
                                <li><a href="#">Mangalsutra</a></li>
                                <li><a href="#">Necklace Set</a></li>
                                <li><a href="#">Pendant Set</a></li>
                                <li><a href="#">Bridal Set</a></li>
                                <li><a href="#">Handmade</a></li>                                
                                <li><a href="#">Kundan</a></li>
                            </ul>
                        </li>                      
                    </ul>
                </li>
                <li class="dropdown menu-large">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Clothing <b class="caret"></b></a>             
                    <ul class="dropdown-menu megamenu row">
                        <li class="col-sm-3">
                            <ul>
                                <li class="dropdown-header">Categories</li>
                                <li class="divider"></li>
                                <li><a href="#">Dresses</a></li>
                                <li><a href="#">Salwar Kameez</a></li>                                
                                <li><a href="#">Wedding Dresses</a></li>
                                
                            </ul>
                        </li>
                        <li class="col-sm-3">
                            <ul>
                                <li class="dropdown-header">New Collections</li>
                                <li class="divider"></li>
                                <li><a href="#">Salwar Suits</a></li>
                                <li><a href="#">Salwar Suits</a></li>
                                <li><a href="#">Salwar Suits</a></li>
                                
                            </ul>
                        </li>                      
                    </ul>
                </li>
                <li class="dropdown menu-large">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sarees <b class="caret"></b></a>             
                    <ul class="dropdown-menu megamenu row">
                        <li class="col-sm-3">
                            <ul>
                                <li class="dropdown-header">Categories</li>
                                <li class="divider"></li>
                                <li><a href="#">Chiffon</a></li>
                                
                                <li><a href="#">Georgette</a></li>                                
                                <li><a href="#">Net</a></li>
                                <li><a href="#">Satin</a></li>
                                <li><a href="#">Cotton Silk</a></li>
                                <li><a href="#">Blouse</a></li>
                            </ul>
                        </li>
                        <li class="col-sm-3">
                            <ul>
                                <li class="dropdown-header">New Collections</li>
                                <li class="divider"></li>
                                <li><a href="#">Traditional</a></li>
                                <li><a href="#">Party Wear</a></li>
                                <li><a href="#">Handwork</a></li>
                                <li><a href="#">Designer</a></li>
                                <li><a href="#">Bollywood</a></li>                                
                                <li><a href="#">Banarasi</a></li>
                            </ul>
                        </li>                      
                    </ul>
                </li>
                <li class="dropdown menu-large">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Featured Product <b class="caret"></b> </a>
                    <ul class="dropdown-menu megamenu row">
                        <li>
                            <div class="col-sm-6 col-md-2">
                                <a href="#" class="thumbnail">
                                <!-- <img src="http://placehold.it/150x120" /> -->
                                <img src="<?php echo $this->getSkinUrl();?>img/12.jpg" />
                                <img src="<?php echo $this->getSkinUrl();?>img/price.png" />
                                </a>
                            </div>
                            <div class="col-sm-6 col-md-2">
                                <a href="#" class="thumbnail">
                                <img src="<?php echo $this->getSkinUrl();?>img/14.jpg" />
                                <img src="<?php echo $this->getSkinUrl();?>img/price.png" />
                                </a>
                            </div>
                            <div class="col-sm-6 col-md-2">
                                <a href="#" class="thumbnail">
                                <img src="<?php echo $this->getSkinUrl();?>img/12.jpg" />
                                <img src="<?php echo $this->getSkinUrl();?>img/price.png" />
                                </a>
                            </div>
                            <div class="col-sm-6 col-md-2">
                                <a href="#" class="thumbnail">
                                <img src="<?php echo $this->getSkinUrl();?>img/14.jpg" />
                                <img src="<?php echo $this->getSkinUrl();?>img/price.png" />
                                </a>
                            </div>
                            <div class="col-sm-6 col-md-2">
                                <a href="#" class="thumbnail">
                                <img src="<?php echo $this->getSkinUrl();?>img/14.jpg" />
                                <img src="<?php echo $this->getSkinUrl();?>img/price.png" />
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

<!--mega dropdown -->
