<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 *
 *
 *
 * Template for Mage_Page_Block_Html
 */
?>
<?php 
/*****/ 
$custompatern = MAGE::helper('ThemeOptions')->getThemeOptions('custompatern');
$bgPatern = $paternurl = $mediaurl = "";
if (!$custompatern):
    $bgPatern = MAGE::helper('ThemeOptions')->getThemeOptions('patern');
else:
    $mediaurl = MAGE::helper('ThemeOptions')->getThemeOptions('mediaurl');
    $paternurl = 'style="background:url('.$mediaurl.$custompatern.') center top repeat;"';
endif;
/*****/
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$bgPatern.$this->getBodyClass().'"':'' ?> <?php echo $paternurl; ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('header') ?>
<?php echo $this->getChildHtml('breadcrumbs') ?>
<div class="content-wrapper">
    <div class="container_12">    
        <div class="main-container col3-layout">
            <aside class="grid_3 sidebar">
                <?php // Predefined Static Block
                if ($static_html = $this->getChildHtml('sidebar_top_block')):
                    echo '<div class="sidebar-top-block">'.$static_html.'</div>';
                endif; ?>
                <?php echo $this->getChildHtml('left') ?>
                <?php // Predefined Static Block
                    if ($static_html = $this->getChildHtml('sidebar_bottom_block')):
                        echo '<div class="sidebar-bottom-block">'.$static_html.'</div>';
                    endif; ?>
            </aside>
            <div class="sidebar-switcher">
                <?php echo $this->__('Sidebar:'); ?><a class="on active"><?php echo $this->__('ON'); ?></a><span class="divider"></span><a class="off"><?php echo $this->__('OFF'); ?></a>
            </div>
            <div class="grid_6 col-main">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>
            <aside class="grid_3 sidebar"><?php echo $this->getChildHtml('right') ?></aside>
            <div class="clear"></div>
        </div>    
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>