<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<?php 
    $cartpage = MAGE::helper('ThemeOptions')->getThemeOptions('cartpage');
?>
<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
        <?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
        <?php foreach ($this->getMethods('top_methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        <br class="clear" />
    </div>
    <div class="mobile-container">
        <?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
        <?php foreach ($this->getMethods('top_methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        <div class="clear"></div>
    </div>
    
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <?php if ($cartpage == 'cart_standard'): ?>
    <div class="cart-column grid_9 alpha">
    <?php endif; ?>
        <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
            <fieldset>
                <table id="shopping-cart-table" class="data-table cart-table<?php if ($cartpage == 'cart_accordion'){echo ' accordion-mode';} ?>">
                
                <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                    <tfoot>
                        <tr class="buttons-row">
                            <td colspan="2" class="a-right buttons">
                                <div>
                                    <?php if($this->getContinueShoppingUrl()): ?>
                                        <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                                    <?php endif; ?>
                                    <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-clear"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                                    <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                    <tbody>
                    <?php foreach($this->getItems() as $item_key => $_item): ?>
                    <?php if(($item_key%1)): ?>
                    <tr>
                    <?php endif; ?>
                        <td<?php if(count($this->getItems()) == 1 ){echo ' class="only-one"';}; ?>>
                            <div class="product-box"><?php echo $this->getItemHtml($_item) ?></div>
                        </td>
                    <?php if(($item_key%2)): ?>
                    </tr>
                    <?php endif; ?>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('shopping-cart-table')</script>
            </fieldset>
        </form>
    <?php if ($cartpage == 'cart_standard'): ?>
    </div>
    <?php endif; ?>
    <?php if ($cartpage == 'cart_standard'): ?>
        <div class="cart-collaterals standard grid_3 omega">
            <?php echo $this->getChildHtml('coupon') ?>
            <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
            <div class="totals">
                <div class="totals-border">
                    <div class="totals-wrapper"><?php echo $this->getChildHtml('totals'); ?></div>
                    <?php if(!$this->hasError()): ?>
                    <ul class="checkout-types">
                    <?php foreach ($this->getMethods('methods') as $method): ?>
                        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                        <li><?php echo $methodHtml; ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="clear"></div>
        <?php if ($this->getChildHtml('crosssell')): ?>
            <?php echo $this->getChildHtml('crosssell') ?>
        <?php endif; ?>
    <?php else: ?>
    <div class="cart-collaterals" id="cart-accordion">
        <?php if ($this->getChildHtml('crosssell')): ?>
        <h3 class="accordion-title"><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h3>
        <div class="accordion-content"><?php echo $this->getChildHtml('crosssell_big') ?></div>
        <?php endif; ?>
        <h3 class="accordion-title"><?php echo $this->__('Discount Codes') ?></h3>
        <div class="accordion-content"><?php echo $this->getChildHtml('coupon') ?></div>
        <?php if (!$this->getIsVirtual()):?> 
        <h3 class="accordion-title"><?php echo $this->__('Estimate Shipping and Tax') ?></h3>
        <div class="accordion-content"><?php echo $this->getChildHtml('shipping'); ?></div>
        <?php endif; ?>
    </div>
    <div class="totals totals-accordion">
        <?php echo $this->getChildHtml('totals'); ?>
        <?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
        <?php foreach ($this->getMethods('methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
    </div>
    <?php endif; ?>
</div>
